### ISSUE TITLE
Replace gulp with npm scripts?

### ISSUE THREAD

**Issue by Meligy** [shibbir/generator-angular2-typescript#2]
Hello,
It's quite common for SystemJS and Webpack to completely replace gulp. So, matching the trends, etc. it might be a good idea to remove gulp. mostly for increasing user base, and to remove the question "Why do you have gulp when you also use systemJS/Webpack?".

The generator doesn't seem to be using gulp for much anyway. It should be possible to convert that into a few npm scripts. Maybe there will be another helper JS file, or might even get away without one.

Is this a welcome idea? Would you like to give it a go? Or prefer having a PR to evaluate?

Just starting the discussion, and happy to give it a go as PR if the idea in general is accepted.

Thanks.

**PS**

This is an AWESOME project. I love. Thanks heaps for creating it.

**Comment by shibbir** [comment]
Hi @Meligy, thanks for the idea. Yes I also thought about it. Actually for a while the generator used only "npm scripts". Then I added **gulp** because it seems if I add more functionality in it, the `package.json` will get cluttered. You are right that at the moment **gulp** isn't doing anything special but it will be :smile:

At the moment I'm not very sure if I should completely remove gulp. I need some time to dig more. For now, may be I will add option to choose between gulp or plain npm scripts?

Some discussions regarding the topic:
- [http://stackoverflow.com/questions/33558396/gulp-webpack-or-just-webpack](url)
- [http://stackoverflow.com/questions/33561272/task-runners-gulp-grunt-etc-and-bundlers-webpack-browserify-why-use-toge](url)
- [http://blog.andrewray.me/webpack-when-to-use-and-why/](url)

Thanks again.

**Comment by shibbir** [comment]
Closed with [#9b58a8f](https://github.com/shibbir/generator-angular2-typescript/commit/9b58a8f239eca81a48d8fdc38dfa7a9821d3d5ae)

Inclusion of [gulp](http://gulpjs.com/) is optional now. The generator will generate equivalent **'npm scripts'** when **gulp** is not available.

**Comment by Meligy** [comment]
Works awesomely :)
