### ISSUE TITLE
is it ready to be used in production?

### ISSUE THREAD

**Issue by axcl** [shibbir/generator-angular2-typescript#23]
Firstly thank you for your amazing work.. it gives me a head start. But is it ready to be used in production release and angular version you are using is 2.0.0 and there many newer releases

**Comment by shibbir** [comment]
Hi @axcl, Thanks. Yes it is ready for production use. And the latest release from angular is `v2.1.2` which has no breaking changes since `v2.0.0` as they are following [SemVer](http://semver.org/). Only some bug fixes and performance improvements are made in the latest releases. That means you can safely use `v2.1.2` in here.
